[package]
name = "built_with_scraper"
version = "0.0.1"
authors = ["Colwyn Fritze-Moor <colwyn@colwyn.me>"]

[dependencies]
config = "0.9"
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"
futures = "0.1.23"
hyper = "0.12"
hyper-tls = "0.3.0"
queryst = "2.0.0"